version: '3'

services:
  basic:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - THREADS=100
      - FOLDER=internal
      - LIMIT=250

  mounted:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - THREADS=100
      - FOLDER=mounted
      - LIMIT=250
    volumes:
      - data:/app/mounted

volumes:
  data: